db_username  = "toucanfortune"
db_pw = "rouedefortune"
db_cluster = "ToucanFortune"
lien = "mongodb+srv://toucanfortune:rouedefortune@toucanfortune.gzo0glz.mongodb.net/?retryWrites=true&writeConcern=majority"
lien2 = "mongodb+srv://st.secrets['db_username']:st.secrets['db_pw']@toucanfortune.gzo0glz.mongodb.net/?retryWrites=true&writeConcern=majority"
